spring:
  social:
    kakao:
      client_id: aaa
      redirect: https://cleanbook.site
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

    naver:
      client_id: aaaa
      client_secret: aaaaa
      redirect: https://cleanbook.site
      url:
        login: https://nid.naver.com/oauth2.0/authorize
        token: https://nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me

  local:
    social:
      kakao:
        client_id: aaa
        redirect: http://localhost:8080/local/social/login/kakao
        url:
          login: https://kauth.kakao.com/oauth/authorize
          token: https://kauth.kakao.com/oauth/token
          profile: https://kapi.kakao.com/v2/user/me

      naver:
        client_id: aaaa
        client_secret: aaaaa
        redirect: http://localhost:8080/local/social/login/naver
        url:
          login: https://nid.naver.com/oauth2.0/authorize
          token: https://nid.naver.com/oauth2.0/token
          profile: https://openapi.naver.com/v1/nid/me


